# Activate Flutter's recommended lints
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # --- Style & Consistency ---
    prefer_single_quotes: true
    always_use_package_imports: true
    avoid_print: true
    unnecessary_const: true
    unnecessary_new: true

    # --- Safety & Correctness ---
    avoid_dynamic_calls: true
    avoid_empty_else: true
    avoid_returning_null_for_future: true
    avoid_slow_async_io: true
    cancel_subscriptions: true
    close_sinks: true

    # --- Code Quality ---
    prefer_final_locals: true
    prefer_final_in_for_each: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_redundant_argument_values: true
    avoid_unused_constructor_parameters: true

    # --- Clean Architecture & Maintainability ---
    avoid_catches_without_on_clauses: true
    avoid_classes_with_only_static_members: false
    avoid_multiple_declarations_per_line: true
    avoid_bool_literals_in_conditional_expressions: true
    require_trailing_commas: true

    # --- Riverpod & State Management Friendly ---
    avoid_setters_without_getters: false
    avoid_private_typedef_functions: false

    # --- Firebase Friendly ---
    avoid_print: true
    avoid_redundant_argument_values: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"
    - "build/**"
    - "lib/firebase_options.dart"

  errors:
    # Treat warnings as errors in CI for strictness
    unused_import: error
    dead_code: error
    missing_required_param: error
    missing_return: error
